In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

from sklearn.neighbors import KNeighborsRegressor


from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error


In [2]:
os.listdir( '../data/preprocessed data' )

['pre-processed_data.csv']

In [3]:
df = pd.read_csv( '../data/preprocessed data/pre-processed_data.csv' )

In [16]:
df.columns

Index(['study_hours', 'class_attendance', 'sleep_hours', 'sleep_quality',
       'facility_rating', 'exam_difficulty', 'exam_score', 'course_diff',
       'gender_female', 'gender_male', 'gender_other',
       'course_Bachelor of Arts', 'course_Bachelor of Business Administration',
       'course_Bachelor of Commerce',
       'course_Bachelor of Computer Applications',
       'course_Bachelor of Science', 'course_Bachelor of Technology',
       'course_Diploma', 'internet_access_no', 'internet_access_yes',
       'study_method_coaching', 'study_method_group study',
       'study_method_mixed', 'study_method_online videos',
       'study_method_self-study'],
      dtype='object')

In [46]:
df.sample(3)

,study_hours,class_attendance,sleep_hours,sleep_quality,facility_rating,exam_difficulty,exam_score,course_diff,gender_female,gender_male,...,course_Bachelor of Science,course_Bachelor of Technology,course_Diploma,internet_access_no,internet_access_yes,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
6201,0.71,76.4,5.7,1,2,2,59.1,5,0,1,...,1,0,0,0,1,1,0,0,0,0
8567,2.82,84.8,7.6,1,1,1,77.1,5,0,0,...,1,0,0,0,1,0,0,1,0,0
6564,0.08,63.0,4.3,0,2,1,28.5,1,1,0,...,0,0,0,0,1,0,0,0,0,1


In [48]:
df.shape

(20000, 25)

In [65]:
No_of_students = len(df)
#study_hours_mean  = int(df["study_hours"].mean())
#study_hours_mean  = df["study_hours"].value_counts().sum()
course_diffeculty = df["course_diff"].unique()
min_exam_score= df["exam_score"].min()
max_exam_score= df["exam_score"].max()




No_of_students, course_diffeculty, min_exam_score, max_exam_score

(20000, array([0, 4, 5, 6, 3, 1, 2]), np.float64(19.599), np.float64(100.0))

In [50]:
Female = df["gender_female"].value_counts()

Female

gender_female
0    13421
1     6579
Name: count, dtype: int64

In [56]:
df["exam_difficulty"].unique()

array([2, 1, 0])

In [ ]:
df["study_hours"].mean(), 

(np.float64(4.0076035), np.float64(0.9966), np.float64(0.892))

In [ ]:
df["class_attendance"]

# Slider for calss attendance

0        92.9
1        64.8
2        76.8
3        48.4
4        71.6
         ... 
19995    71.3
19996    41.6
19997    68.2
19998    76.3
19999    47.9
Name: class_attendance, Length: 20000, dtype: float64

In [ ]:
df["sleep_quality"].unique()

# Filter for sleep quality

array([0, 1, 2])

In [ ]:
df["exam_difficulty"].unique()

# Filter for  exam difficulty

array([2, 1, 0])

In [23]:
df["gender_female"].value_counts()[1]


# filter for gender Female

np.int64(6579)

In [25]:
df["gender_male"].value_counts()[1]

# filter for gender male

np.int64(6695)

In [26]:
df["gender_other"].value_counts()[1]

# filter for gender ohter

np.int64(6726)

In [70]:
px.histogram(df, x= 'study_hours',y= 'exam_score')